name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v2.5.3
        - uses: tuist/tuist-action@0.13.0
          with:
            command: 'fetch'
            arguments: ''
        - uses: tuist/tuist-action@0.13.0
          with:
            command: 'build'
            arguments: ''
