name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v3
        - uses: tuist/tuist-actions@0.13.0
            with:
                command: 'fetch'
                arguments: ''
        - uses: tuist/tuist-actions@0.13.0
            with:
                command: 'build'
                arguments: ''
