name: Swift

on:
  push:
    branches: [ master, develop, feedback_1 ]
  pull_request:
    branches: [ master, develop, feedback_1 ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v3
        - uses: tuist/tuist-action@0.13.0
          with:
            command: 'fetch'
            arguments: ''
        - uses: tuist/tuist-action@0.13.0
          with:
            command: 'build'
            arguments: ''
